version: '3.2'
services:
  master:
    image: registry.teco.edu/smartaqnet/postgis:9.5-alpine
    build: .
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_REPLICATION_USER=replication
      - POSTGRES_REPLICATION_PASSWORD=ChangeMe
      - POSTGRES_REPLICATION_MASTER=true
    volumes:
      - 'master:/var/lib/postgresql/data:rw'
    networks:
      - traefik
    ports:
      - target: 5432
        published: 15432
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.postgis == master
      labels:
        - 'traefik.enable=true'
        - 'traefik.tcp.routers.psqlm.entrypoints=psql'
        - 'traefik.tcp.routers.psqlm.rule=HostSNI(`*`)'
        - 'traefik.tcp.routers.psqlm.service=psqlm@docker'
        - 'traefik.tcp.services.psqlm.loadbalancer.server.port=5432'
  replica:
    build: .
    image: registry.teco.edu/smartaqnet/postgis:9.5-alpine
    ports:
      - target: 5432
        published: 15432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_REPLICATION_USER=replication
      - POSTGRES_REPLICATION_PASSWORD=ChangeMe
      - POSTGRES_REPLICATION_MASTER_HOST=master
    volumes:
      - 'replica:/var/lib/postgresql/data:rw'
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.postgis == replica
volumes:
  master:
  replica:
networks:
  traefik:
    external:
      name: 'traefik_network'
