/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pw.oliver.jmkb.avroclasses;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** The type of the location, for example Point */
@org.apache.avro.specific.AvroGenerated
public class LocationType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4074392992138055766L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocationType\",\"namespace\":\"pw.oliver.jmkb.avroclasses\",\"doc\":\"The type of the location, for example Point\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"doc\":\"Name of the LocationType\"},{\"name\":\"coordinates\",\"type\":\"string\",\"doc\":\"Coordinates for the LocationType\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LocationType> ENCODER =
      new BinaryMessageEncoder<LocationType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LocationType> DECODER =
      new BinaryMessageDecoder<LocationType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<LocationType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<LocationType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LocationType>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this LocationType to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a LocationType from a ByteBuffer. */
  public static LocationType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of the LocationType */
  @Deprecated public java.lang.CharSequence type;
  /** Coordinates for the LocationType */
  @Deprecated public java.lang.CharSequence coordinates;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LocationType() {}

  /**
   * All-args constructor.
   * @param type Name of the LocationType
   * @param coordinates Coordinates for the LocationType
   */
  public LocationType(java.lang.CharSequence type, java.lang.CharSequence coordinates) {
    this.type = type;
    this.coordinates = coordinates;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return coordinates;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.CharSequence)value$; break;
    case 1: coordinates = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return Name of the LocationType
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * Name of the LocationType
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'coordinates' field.
   * @return Coordinates for the LocationType
   */
  public java.lang.CharSequence getCoordinates() {
    return coordinates;
  }

  /**
   * Sets the value of the 'coordinates' field.
   * Coordinates for the LocationType
   * @param value the value to set.
   */
  public void setCoordinates(java.lang.CharSequence value) {
    this.coordinates = value;
  }

  /**
   * Creates a new LocationType RecordBuilder.
   * @return A new LocationType RecordBuilder
   */
  public static pw.oliver.jmkb.avroclasses.LocationType.Builder newBuilder() {
    return new pw.oliver.jmkb.avroclasses.LocationType.Builder();
  }

  /**
   * Creates a new LocationType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LocationType RecordBuilder
   */
  public static pw.oliver.jmkb.avroclasses.LocationType.Builder newBuilder(pw.oliver.jmkb.avroclasses.LocationType.Builder other) {
    return new pw.oliver.jmkb.avroclasses.LocationType.Builder(other);
  }

  /**
   * Creates a new LocationType RecordBuilder by copying an existing LocationType instance.
   * @param other The existing instance to copy.
   * @return A new LocationType RecordBuilder
   */
  public static pw.oliver.jmkb.avroclasses.LocationType.Builder newBuilder(pw.oliver.jmkb.avroclasses.LocationType other) {
    return new pw.oliver.jmkb.avroclasses.LocationType.Builder(other);
  }

  /**
   * RecordBuilder for LocationType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocationType>
    implements org.apache.avro.data.RecordBuilder<LocationType> {

    /** Name of the LocationType */
    private java.lang.CharSequence type;
    /** Coordinates for the LocationType */
    private java.lang.CharSequence coordinates;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pw.oliver.jmkb.avroclasses.LocationType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.coordinates)) {
        this.coordinates = data().deepCopy(fields()[1].schema(), other.coordinates);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LocationType instance
     * @param other The existing instance to copy.
     */
    private Builder(pw.oliver.jmkb.avroclasses.LocationType other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.coordinates)) {
        this.coordinates = data().deepCopy(fields()[1].schema(), other.coordinates);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * Name of the LocationType
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * Name of the LocationType
      * @param value The value of 'type'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.LocationType.Builder setType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * Name of the LocationType
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * Name of the LocationType
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.LocationType.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'coordinates' field.
      * Coordinates for the LocationType
      * @return The value.
      */
    public java.lang.CharSequence getCoordinates() {
      return coordinates;
    }

    /**
      * Sets the value of the 'coordinates' field.
      * Coordinates for the LocationType
      * @param value The value of 'coordinates'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.LocationType.Builder setCoordinates(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.coordinates = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'coordinates' field has been set.
      * Coordinates for the LocationType
      * @return True if the 'coordinates' field has been set, false otherwise.
      */
    public boolean hasCoordinates() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'coordinates' field.
      * Coordinates for the LocationType
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.LocationType.Builder clearCoordinates() {
      coordinates = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LocationType build() {
      try {
        LocationType record = new LocationType();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.coordinates = fieldSetFlags()[1] ? this.coordinates : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LocationType>
    WRITER$ = (org.apache.avro.io.DatumWriter<LocationType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LocationType>
    READER$ = (org.apache.avro.io.DatumReader<LocationType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
