/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pw.oliver.jmkb.avroclasses;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** A Sensor is an instrument that observes a property or phenomenon with the goal of producing an estimate of the value of the property. */
@org.apache.avro.specific.AvroGenerated
public class Sensor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8690380604646401756L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sensor\",\"namespace\":\"pw.oliver.jmkb.avroclasses\",\"doc\":\"A Sensor is an instrument that observes a property or phenomenon with the goal of producing an estimate of the value of the property.\",\"fields\":[{\"name\":\"iotId\",\"type\":\"string\",\"doc\":\"iotId of this Sensor\"},{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Name of the Sensor\"},{\"name\":\"description\",\"type\":\"string\",\"doc\":\"Description of the Sensor\"},{\"name\":\"encodingType\",\"type\":\"string\",\"doc\":\"Encoding type of the Sensor\"},{\"name\":\"metadata\",\"type\":\"string\",\"doc\":\"Metadata of the Sensor\"},{\"name\":\"Datastreams\",\"type\":[\"null\",\"string\"],\"doc\":\"Datastreams associated with this Sensor\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sensor> ENCODER =
      new BinaryMessageEncoder<Sensor>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sensor> DECODER =
      new BinaryMessageDecoder<Sensor>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sensor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sensor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sensor>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sensor to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sensor from a ByteBuffer. */
  public static Sensor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** iotId of this Sensor */
  @Deprecated public java.lang.CharSequence iotId;
  /** Name of the Sensor */
  @Deprecated public java.lang.CharSequence name;
  /** Description of the Sensor */
  @Deprecated public java.lang.CharSequence description;
  /** Encoding type of the Sensor */
  @Deprecated public java.lang.CharSequence encodingType;
  /** Metadata of the Sensor */
  @Deprecated public java.lang.CharSequence metadata;
  /** Datastreams associated with this Sensor */
  @Deprecated public java.lang.CharSequence Datastreams;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sensor() {}

  /**
   * All-args constructor.
   * @param iotId iotId of this Sensor
   * @param name Name of the Sensor
   * @param description Description of the Sensor
   * @param encodingType Encoding type of the Sensor
   * @param metadata Metadata of the Sensor
   * @param Datastreams Datastreams associated with this Sensor
   */
  public Sensor(java.lang.CharSequence iotId, java.lang.CharSequence name, java.lang.CharSequence description, java.lang.CharSequence encodingType, java.lang.CharSequence metadata, java.lang.CharSequence Datastreams) {
    this.iotId = iotId;
    this.name = name;
    this.description = description;
    this.encodingType = encodingType;
    this.metadata = metadata;
    this.Datastreams = Datastreams;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return iotId;
    case 1: return name;
    case 2: return description;
    case 3: return encodingType;
    case 4: return metadata;
    case 5: return Datastreams;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: iotId = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: description = (java.lang.CharSequence)value$; break;
    case 3: encodingType = (java.lang.CharSequence)value$; break;
    case 4: metadata = (java.lang.CharSequence)value$; break;
    case 5: Datastreams = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'iotId' field.
   * @return iotId of this Sensor
   */
  public java.lang.CharSequence getIotId() {
    return iotId;
  }

  /**
   * Sets the value of the 'iotId' field.
   * iotId of this Sensor
   * @param value the value to set.
   */
  public void setIotId(java.lang.CharSequence value) {
    this.iotId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Name of the Sensor
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * Name of the Sensor
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return Description of the Sensor
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * Description of the Sensor
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'encodingType' field.
   * @return Encoding type of the Sensor
   */
  public java.lang.CharSequence getEncodingType() {
    return encodingType;
  }

  /**
   * Sets the value of the 'encodingType' field.
   * Encoding type of the Sensor
   * @param value the value to set.
   */
  public void setEncodingType(java.lang.CharSequence value) {
    this.encodingType = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return Metadata of the Sensor
   */
  public java.lang.CharSequence getMetadata() {
    return metadata;
  }

  /**
   * Sets the value of the 'metadata' field.
   * Metadata of the Sensor
   * @param value the value to set.
   */
  public void setMetadata(java.lang.CharSequence value) {
    this.metadata = value;
  }

  /**
   * Gets the value of the 'Datastreams' field.
   * @return Datastreams associated with this Sensor
   */
  public java.lang.CharSequence getDatastreams() {
    return Datastreams;
  }

  /**
   * Sets the value of the 'Datastreams' field.
   * Datastreams associated with this Sensor
   * @param value the value to set.
   */
  public void setDatastreams(java.lang.CharSequence value) {
    this.Datastreams = value;
  }

  /**
   * Creates a new Sensor RecordBuilder.
   * @return A new Sensor RecordBuilder
   */
  public static pw.oliver.jmkb.avroclasses.Sensor.Builder newBuilder() {
    return new pw.oliver.jmkb.avroclasses.Sensor.Builder();
  }

  /**
   * Creates a new Sensor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sensor RecordBuilder
   */
  public static pw.oliver.jmkb.avroclasses.Sensor.Builder newBuilder(pw.oliver.jmkb.avroclasses.Sensor.Builder other) {
    return new pw.oliver.jmkb.avroclasses.Sensor.Builder(other);
  }

  /**
   * Creates a new Sensor RecordBuilder by copying an existing Sensor instance.
   * @param other The existing instance to copy.
   * @return A new Sensor RecordBuilder
   */
  public static pw.oliver.jmkb.avroclasses.Sensor.Builder newBuilder(pw.oliver.jmkb.avroclasses.Sensor other) {
    return new pw.oliver.jmkb.avroclasses.Sensor.Builder(other);
  }

  /**
   * RecordBuilder for Sensor instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sensor>
    implements org.apache.avro.data.RecordBuilder<Sensor> {

    /** iotId of this Sensor */
    private java.lang.CharSequence iotId;
    /** Name of the Sensor */
    private java.lang.CharSequence name;
    /** Description of the Sensor */
    private java.lang.CharSequence description;
    /** Encoding type of the Sensor */
    private java.lang.CharSequence encodingType;
    /** Metadata of the Sensor */
    private java.lang.CharSequence metadata;
    /** Datastreams associated with this Sensor */
    private java.lang.CharSequence Datastreams;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pw.oliver.jmkb.avroclasses.Sensor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.iotId)) {
        this.iotId = data().deepCopy(fields()[0].schema(), other.iotId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.encodingType)) {
        this.encodingType = data().deepCopy(fields()[3].schema(), other.encodingType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.metadata)) {
        this.metadata = data().deepCopy(fields()[4].schema(), other.metadata);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Datastreams)) {
        this.Datastreams = data().deepCopy(fields()[5].schema(), other.Datastreams);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sensor instance
     * @param other The existing instance to copy.
     */
    private Builder(pw.oliver.jmkb.avroclasses.Sensor other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.iotId)) {
        this.iotId = data().deepCopy(fields()[0].schema(), other.iotId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.encodingType)) {
        this.encodingType = data().deepCopy(fields()[3].schema(), other.encodingType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.metadata)) {
        this.metadata = data().deepCopy(fields()[4].schema(), other.metadata);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Datastreams)) {
        this.Datastreams = data().deepCopy(fields()[5].schema(), other.Datastreams);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'iotId' field.
      * iotId of this Sensor
      * @return The value.
      */
    public java.lang.CharSequence getIotId() {
      return iotId;
    }

    /**
      * Sets the value of the 'iotId' field.
      * iotId of this Sensor
      * @param value The value of 'iotId'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder setIotId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.iotId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'iotId' field has been set.
      * iotId of this Sensor
      * @return True if the 'iotId' field has been set, false otherwise.
      */
    public boolean hasIotId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'iotId' field.
      * iotId of this Sensor
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder clearIotId() {
      iotId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Name of the Sensor
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * Name of the Sensor
      * @param value The value of 'name'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Name of the Sensor
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Name of the Sensor
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * Description of the Sensor
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * Description of the Sensor
      * @param value The value of 'description'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * Description of the Sensor
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * Description of the Sensor
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'encodingType' field.
      * Encoding type of the Sensor
      * @return The value.
      */
    public java.lang.CharSequence getEncodingType() {
      return encodingType;
    }

    /**
      * Sets the value of the 'encodingType' field.
      * Encoding type of the Sensor
      * @param value The value of 'encodingType'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder setEncodingType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.encodingType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'encodingType' field has been set.
      * Encoding type of the Sensor
      * @return True if the 'encodingType' field has been set, false otherwise.
      */
    public boolean hasEncodingType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'encodingType' field.
      * Encoding type of the Sensor
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder clearEncodingType() {
      encodingType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * Metadata of the Sensor
      * @return The value.
      */
    public java.lang.CharSequence getMetadata() {
      return metadata;
    }

    /**
      * Sets the value of the 'metadata' field.
      * Metadata of the Sensor
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder setMetadata(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.metadata = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * Metadata of the Sensor
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'metadata' field.
      * Metadata of the Sensor
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'Datastreams' field.
      * Datastreams associated with this Sensor
      * @return The value.
      */
    public java.lang.CharSequence getDatastreams() {
      return Datastreams;
    }

    /**
      * Sets the value of the 'Datastreams' field.
      * Datastreams associated with this Sensor
      * @param value The value of 'Datastreams'.
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder setDatastreams(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.Datastreams = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'Datastreams' field has been set.
      * Datastreams associated with this Sensor
      * @return True if the 'Datastreams' field has been set, false otherwise.
      */
    public boolean hasDatastreams() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'Datastreams' field.
      * Datastreams associated with this Sensor
      * @return This builder.
      */
    public pw.oliver.jmkb.avroclasses.Sensor.Builder clearDatastreams() {
      Datastreams = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sensor build() {
      try {
        Sensor record = new Sensor();
        record.iotId = fieldSetFlags()[0] ? this.iotId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.encodingType = fieldSetFlags()[3] ? this.encodingType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.metadata = fieldSetFlags()[4] ? this.metadata : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.Datastreams = fieldSetFlags()[5] ? this.Datastreams : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sensor>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sensor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sensor>
    READER$ = (org.apache.avro.io.DatumReader<Sensor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
