version: '3'
services:
  netdata:
    image: swarm-manager-1:5001/smartaqnet/netdata:v1.19.0
    build: ../netdata
  netdata-slave:
    image: swarm-manager-1:5001/smartaqnet/netdata:v1.19.0
    build:
      context: ../netdata
      dockerfile: ./Dockerfile-slave