version: '3.2'
services:
  master:
    image: swarm-manager-1:5000/smartaqnet/postgis:9.5-alpine
    build: ../postgis
  replica:
    image: swarm-manager-1:5000/smartaqnet/postgis:9.5-alpine
    build: ../postgis