version: "3.8"
services:
  netdata:
    configs:
      - source: health_alarm_notify
        target: /etc/netdata/health_alarm_notify.conf
        template_driver: golang
    secrets:
      - telegram_bot_token
      - default_recipient_telegram
configs:
  health_alarm_notify:
    file: ./health_alarm_notify.conf
secrets:
  telegram_bot_token:
    file: ./secrets/TELEGRAM_BOT_TOKEN
  default_recipient_telegram:
    file: ./secrets/DEFAULT_RECIPIENT_TELEGRAM