version: '3'

services:
    kafka:
       image: landoop/fast-data-dev 
       environment:
           - SAMPLEDATA=0
           - RUNTESTS=0
           - ADV_HOST=193.196.37.73
       ports:
           - 3030:3030
           - 3031:3031
           - 8081:8081
           - 8082:8082
           - 8083:8083
           - 2181:2181
           - 9092:9092
       volumes:
           - /var/kafka/:/data
